version: '3.8'
services:
  app:
    image: fkrafi/springboot-docker:eclipse-temurin-21-jre
    environment:
      APP_JAR: /demo-0.0.1-SNAPSHOT.jar
      APP_NAME: my-spring-app
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./demo-0.0.1-SNAPSHOT.jar:/demo-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    restart: unless-stopped
